version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - tar -cvzf riches.tgz .
artifacts:
  files:
    - riches.tgz
    
test:
  date: 2020-03-30
  change: 4



